### ISSUE TITLE
Firefox/chrome plugin

### ISSUE THREAD

**Issue by tapir** [nextcloud/passman#138]
Any chance we get a browser plugin in the future? Without it any password manager is only half useful.

**Comment by animalillo** [comment]
Yes, we are thinking about it. We might start with a firefox plugin.
Just curious, what features would you like to see in such a plugin?

**Comment by tapir** [comment]
I actually use and very much like firefox plugin for @fcturner's owncloud password app.
It literally does nothing more than fetch all your passwords and insert them to the form when user clicks the button on the toolbar. It also notifies you if the web page you're on has a password registered on the database.

![untitled](https://cloud.githubusercontent.com/assets/223984/21427506/0ef45888-c866-11e6-9916-92643cf1ae65.png)

**Comment by brantje** [comment]
Nice, can you link us the addon page?

**Comment by tapir** [comment]
https://github.com/eglia/ff-oc-passwords

Here it is. If your API resembles the owncloud password app maybe it's just a matter of simple fork 😉

**Comment by animalillo** [comment]
neeeeat! thanks! we will definitely take a look into this app!!

**Comment by brantje** [comment]
Seems that the app oc-password, saves the passwords un-encrypted, can you confirm that's the case?

**Comment by tapir** [comment]
The owncloud app keeps them encrypted.

You can set the firefox plugin to use the firefox master password or not. I don't know if that means it's encrypting them.

**Comment by tapir** [comment]
Warning: This will save your credentials locally. To ensure safety, set a master password in the firefox settings!

This is the comment in plugin's settings window.

**Comment by fcturner** [comment]
> Seems that the app oc-password, saves the passwords un-encrypted, can you confirm that's the case?

Are you nuts? :wink:
My Passwords app for ownCloud and NextCloud saves passwords really really well encrypted, much more safe than the way NC and OC encrypt passwords. The master password is for app access only (web gui) and is saved encrypted too.

**Comment by animalillo** [comment]
@fcturner how does it encrypt stuff? a quick search trough the code showed no hints about encryption, would be nice to know the encryption mechanisms used by the app!

**Comment by fcturner** [comment]
Huh? It really don't see why you would assume that I don't encrypt everything a user puts in. It's stated in my readme and if you review the entries in the database you would've seen that everything is encrypted. 

I just coded as I was lead by the developers tutorial by ownCloud. I'm really surprised that you couldn't find the encryption part since you are ownCloud app developers too. 

It can be found in service/passwordservice.php. Search for 'class Encryption'. 

From my readme:
* Encryption is done using a key built from user-specific, ownCloud/NextCloud-specific, and database entry-specific data so it is unique for every encrypted block of text (i.e. every password). It therefore provides key rotation for cipher and authentication keys.
* The keys are not used directly. Instead, it uses [key stretching](http://en.wikipedia.org/wiki/Key_stretching) which relies on [Password-Based Key Derivation Function 2](http://en.wikipedia.org/wiki/PBKDF2) (PBKDF2).
* It uses [Encrypt-then-MAC](http://en.wikipedia.org/wiki/Authenticated_encryption#Approaches_to_Authenticated_Encryption) (EtM), which is a very good method for ensuring the authenticity of the encrypted data.
* It uses mcrypt to perform the encryption using [MCRYPT_BLOWFISH ciphers](https://en.wikipedia.org/wiki/Blowfish_(cipher)) and [MCRYPT_MODE_CBC](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_Block_Chaining_.28CBC.29) for the mode. It's strong enough, and still fairly fast.
* It hides the [Initialization vector](http://en.wikipedia.org/wiki/Initialization_vector) (IV).
* It uses a [timing-safe comparison](http://blog.ircmaxell.com/2014/11/its-all-about-time.html) function using [double Hash-based Message Authentication Code](http://en.wikipedia.org/wiki/Hash-based_message_authentication_code) (HMAC) verification of the source data.

**Comment by fcturner** [comment]
Being sort of a cryptologist, I think it's safe to say that I know what I'm doing :wink:

**Comment by fcturner** [comment]
One more thing; administrators cannot decrypt and view passwords of users. My app perfectly respects the privacy of every user.

**Comment by brantje** [comment]
I just looked at the client side part for encryption, as that is where i expected the encryption happening.
Passman does't has any server side encryption since everything happens client side.

Do you mind if i borrow some parts from the firefox plugin for a passman firefox addon?

**Comment by fcturner** [comment]
I absolutely don't mind if you use it, that's what open source software is for! 

I decided to encrypt both server side and client side (server side encryption with a key that isn't known to the server). Doing so allows creating and editing passwords using a restful api. And that opens the doors to every form of app, plugin, add-on ...

**Comment by animalillo** [comment]
@fcturner sorry for not looking that deeply in the code, and i checked the readme of the plugin thinking it was the one of the actual app and also, like @brantje , i only checked client side code and the main controller but anyway, anything touching the server is subject to easy intervention, but it's good to know there is some encryption on it, thanks for the info ^^

**Comment by brantje** [comment]
Cleaned up the issue abit, old comments are still available [here](http://i.imgur.com/r9iq72q.png)

**Comment by brantje** [comment]
@fcturner Is your extension a webextension or a bootstrapped one? 
You and @tapir are welcome in our telegram group: @passman_dev

**Comment by fcturner** [comment]
Thanks for the offer. It's not my extension, just my app. I only created a secure RestFUL API so others could create extensions. 
Almost anything on the database side of my app can be edited with curl using the correct credentials. So anyone cloud create a web app, Android/iOS app, you name it.

**Comment by brantje** [comment]
We can continue discuession here: https://github.com/brantje/passman-chrome/issues/1

**Comment by brantje** [comment]
Extension for chrome is released: https://chrome.google.com/webstore/detail/hlpjhlifkgmoibhollggngbbhbejecph

Firefox, it is in the store, but awaiting mozilla's review:
https://addons.mozilla.org/en-US/firefox/addon/passman/

**Comment by cwmke** [comment]
The Firefox link doesn't currently show the extension. Is this still under review?

**Comment by chrislachance** [comment]
I can't find the sign in option once I install Passman for Firefox (Android). Is that coming soon?

**Comment by brantje** [comment]
https://github.com/nextcloud/passman-webextension/issues/75
