### ISSUE TITLE
Use NextCloud's own server-side encryption

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman#279]
Just a question whether I understood the encryption correctly:
1) SCJL used to locally encrypt data
2) Some encryption using `aes-256-cbc` is performed on the server
3) Now this data is stored with NextCloud's default data storage, so all encryption setup in NextCloud is used now?

Or is it somehow stored in the database?

**Edit:** I'd suggest you to change the encryption to e.g. skip the self-made implementation in 2 and just use NextCloud's own [encryption](https://docs.nextcloud.com/server/11/admin_manual/configuration_files/encryption_configuration.html), which is already user-specific.

**Comment by animalillo** [comment]
vault items are encrypted clientside(local) with SJCL using AES-256-CBC with the user key.
the encrypted items are sent to the server where they are reecnrypted with a multipart, stretched key, after this they are sent to the database storage engine, which is plaintext (our plaintext is double encrypted data).

This is made to make it hard in the event of somebody getting the raw data from the database by any means, so they would need to know (or bruteforce) a few keys to get the original items.

**Comment by rugk** [comment]
Okay, so I'll change the topic, because I don't like at all that this is stored in the database. I'd say one can more easily get database content than the file content managed by NextCloud.

**Comment by animalillo** [comment]
No, you did not understand how is this stored, it's fully encrypted, encrypted twice, then stored, which is safer than the standard file storage (only one password there)

**Comment by brantje** [comment]
Good luck cracking the hash. Also if you server is compromised your db and files are compromised. So either way, they will be able to get the hash.
The password is encrypted TWICE with aes256-cbc, good luck cracking that.

**Comment by brantje** [comment]
```
Edit: I'd suggest you to change the encryption to e.g. skip the self-made implementation in 2 and just use NextCloud's own encryption, which is already user-specific.
```
User specific stuff is pain with sharing.
Further more, we use SJCL with has been audited (client side)
Server side we use openssl for encryption
So that is our 'Self made implementation'.

**Comment by rugk** [comment]
This does not matter. I don't think about cracking anything. If the password is weak it does not help. And if the server is compromised all data, also the config including the salts are compromised, so that could be problematic. Anyway, what I basically propose is the following encryption layer:

1) Local, client-side encryption as usual.
2) Now instead of your custom encryption just use NextCloud's encryption.

That's also encrypted twice. Where it is stored does not matter much indeed, but you do not need to invent your own crypto hee, but just use the one that NextCloud already supports.

**Comment by rugk** [comment]
Yeah, I am not criticising your encryption, OpenSSL and so on is fine. [Apart from some things…](https://github.com/nextcloud/passman/issues/280).

The sharing seems a valid issue, but somehow also NextCloud's files app can share files, so would not that be possible to also use here?

**Comment by brantje** [comment]
User specific encryption stuff is a pain with sharing.
Your welcome to implement it though.

**Comment by animalillo** [comment]
There is a setting on the nextcloud admin to request a minium vault password strength, so thats not an issue

**Comment by brantje** [comment]
`The sharing seems a valid issue, but somehow also NextCloud's files app can share files, so would not that be possible to also use here?` 
They use only server side encryption afaik, not client side.

**Comment by rugk** [comment]
Yes, for sure. I am also not in the details of how you do it, but it seems you solved the JS encryption sharing issue. And as this issue is only about changing the server-side encryption, I think you can stick to the way you handle the client-side encryption when sharing and only change the server-side mechanism, can't you?

**Comment by animalillo** [comment]
Let me explain why we won't use files encryption for passman and what can you do if you want it that badly.
1. Files encryption needs another app to be installed, enabled and configured to work
1. To make sharing feasible all password items should be an individual file, making it a load nightmare for te server to decrypt and aggregate and format.
1. Our encryption is as secure or even more than the files encryption one as one of the keys, the one used to encrypt on the client side, never ever reaches the server.
1. Searches and updates would be another nightmare since we would have to implement some sort of file storage system using obscure nextcloud apis and keeping compatibility with owncloud.
1. Some other problems that will certainly arise while developing this and we don't want to deal with as is so incredibly more easily to use our current system.

Now to the encryption we do: We didn't implement our own encryption; we use standard encryption algorithms, proven to be safe and used even by governments to encrypt military data, which imho is safe enough for a password manager.

Now as of what you can do if you want this done this way so badly:
1. Bear in mind we won't drop client side encryption.
1. Create a fork of passman.
1. Once working and fully functional, create a merge request.
1. We will review your merge request.
1. If we think your changes are safe, maintainable and improve performance in any way and or reduce app complexity, we will merge it. 

If you still want to have this feature and don't care of it being merged into main repo:
1. Create a fork.
1. Have fun.

Once we have cleared this matters, i think it's safe to close this issue, feel free to create your merge request at any time.

**Comment by rugk** [comment]
Thanks for the explanation. I think this cleared some things up for me. Somehow I thought you could also use the file encryption in NextCloud without actually writing files or so, which would have reduced the problems you list.
Once this is possible, it may be possible to re-think this idea here. I'll open an issue in the NextCloud repo.

**Comment by animalillo** [comment]
nextcloud encryption is called "files encryption"

**Comment by rugk** [comment]
Yeah… 😇
