### ISSUE TITLE
Folder structure to better organise passwords.

### ISSUE THREAD

**Issue by rkkoszewski** [nextcloud/passman#304]
Hi, I was wondering if having a Folder/File (Tree) structure to organise the passwords could be something interesting for this project. Right now the Tags seems to be a pretty solid way to organise the passwords, but when you have a lot of passwords, the tag list can get pretty huge and gets hard to keep an overview.

A (collapsable) tree structure or stacked tags could make the password managing easier to mantain.

An example structure could be:
```
- Clients
|- Client A
|-|- Databases -> Some passwords here
|-|- Other -> Some passwords here
|- Client B
|-|- Databases -> Some passwords here
|-|- Other -> Some passwords here
|- Personal Passwords
|-|- Databases -> Some passwords here
```

Basically it's not different than just using a tag per folder in the current implementation and stack it. For example to have a Database password for Client A you just create the password with the tags "Clients, Client A, Databases".  

The only downside with the current implementation is that the current "Tag Cloud" would look like:
```
Clients
Client A
Databases
Other
Client B
Personal Passwords
```
Which is not so intuitive as a tree structure, and can get very messy if you have a lot of tags.

An other issue with the Tags is that the user may use Databases or Database tags which would result in two different Tags. A folder structure would resolve that issue.

I guess an other approach is to just use the Vaults as if it would be a Folder, like 3 vaults Client A, Client B, Personal. But here again, if you have a lot of Clients, Personal Stuff or other vaults it will get once again messy and difficult to use.

So I'm just asking if a folder structure could be implemented in Passman, or if such a feature would be even desired or welcomed to this project. What do the developers think about this? Are there any plans to implement such a feature? Would there be any interest on having this if I would implement it (or help if something is being developed right now towards this)? 

Greetings.

**Comment by brantje** [comment]
We had folder structure before, it didn't worked out.
You have a search box where you can quickly search tags.
And imo tags work better than a folder structure.
What you think @animalillo ?

**Comment by rkkoszewski** [comment]
Oww.. what failed? The folder structure could maybe even coexist with the tags.

**Comment by brantje** [comment]
@rkkoszewski As far i know nobody is busy with this. And if the tags can co-exist with the folder structure i'm fine with this. If you need help implementing poke me on telegram. 

I have some idea's about this, let me know if you like to hear them.

**Comment by OS3DrNick** [comment]
@rkkoszewski i would like to comment on this, because when i started to test/use Passman I had the same request basically, the use of some folders. However when using the tags in a good way i found out that it can be 20 times easier to work with tags then with folders. I will explain my with examples.

Structure:
```- Clients
| - aClient
| - | - Database
| - | - Joomla
| - | - Other
| - bClient
| - | - Database
| - | - Other
| - | - Wordpress
| - cClient
| - | - Joomla
| - | - Wordpress
| - dClient
| - | - Other
| - Personal
| - | - Database
| - | - Databases
```

In a normal folder structure you would go to Clients -> bclient -> database, to see the credentials, this would make you client for every credential this deep for at least 3 levels. 

When you use tags the way Passman has implemented them, you don't search in the order you would walk by when you browse folders, but you can randomly pick  your tags.

For example: when i want to search bClient's wordpress password, i would start with 'Wordpress'
(typing `word` and then tab to complete works) which would leave me with bClient and cClient (Also the Tag list shortens!), if i would specify further i would search for the client name 'cClient' this would leave me now with 1 pass. 

Yes if you want to search for 'database' and the tag is 'databases', then it would fail, but that is the same if you type wrong client names, so this is more an administrative guideline to follow then it would be a 'fix/feature'. 

This is my personal experience and my personal opinion, so don't blame the devs on this ;) 

Also with the multi vault support of the Chrome Extension a division of personal and clients can also help with a better structure if you find your lists too long.

**Comment by brantje** [comment]
Closing, you can get this behavior with tags.

**Comment by animalillo** [comment]
I will leave this hint here as of how to use tags:
https://github.com/nextcloud/passman/wiki/TAGS

**Comment by newhinton** [comment]
See this branch:

https://github.com/nextcloud/passman/tree/feature/noid/folder

It is currently in development, and may or may not be released with the app in the future. Also, it is not finished and contains bugs which i intend to fix in the next time.
