### ISSUE TITLE
Import from BitWarden

### ISSUE THREAD

**Issue by eliohann** [nextcloud/passman#404]
## Feature request

**User type**: Logged-in
**User level**: intermediate

### Description
Hi,

I'm using Bitwarden for password management but i want to go self-hosted.
There is no choice to import from bitwarden.
Can you add choice for importing from it ?
Or tell me which already here import option would fit.

### Benefit / value
New user base from bitwarden ;)

**Comment by violoncelloch** [comment]
If bitwarden allows export as .csv you can use the generic / custom csv importer

**Comment by brantje** [comment]
@violoncelloch Has given a appropriate answer, instead of making importers for multiple password managers, i created a generic CSV importer. If that one doesn't export enough information, then we could look into making a native importer. Closing this one as the generic importer could be used. Feel free to open a new issue if importing from bitwarden is a problem.

**Comment by Kitanit** [comment]
@brantje found a stop when importing from BitWarden
*already stuck like this for a couple of minutes, the server is not loaded
![image](https://user-images.githubusercontent.com/65107731/168229453-10349f3c-a570-46e0-bfe7-ebfc11f6bf7e.png)

**Comment by animalillo** [comment]
Given the age of this issue i think it would be better to open a new one and attach any logs on the JS console and server, if any
