### ISSUE TITLE
crypted export of safe [enhancement]

### ISSUE THREAD

**Issue by remraz** [nextcloud/passman#633]
## Feature request

**User type**: Logged-in

**User level**: Beginners

### Description

Export of safe in a still crypted way. Today, export of safe gives clear text information.

### Benefit / value

It would enable moving a safe safely.

### Risk / caveats

None identified.

### Sponsorship

I have no idea how much time it would take and doubt I can offer enough to make it worth. Yet I may give a little...
 
**Are you a developer willing or able to implement this feature?**: No, unfortunately.

**Can you sponsor the development of this feature or do you know someone who can?**: No, but I will ask my Nextcloud service provider.

**Comment by newhinton** [comment]
What benefit do you expect from this? Do other apps support encrypted import?
What use-case do you have in mind?

**Comment by Wadera** [comment]
I like an idea of export availability. Let's use some other open source format like keepass!

**Comment by bblonski** [comment]
I'd like to be able to export in kdbx format.  In cases where I don't have direct access to Nextcloud (such as server going down or restricted internet access), I'd like to have the kdbx file synced locally to my device as well.  That way I could open the file with KeePass or similar software.

**Comment by newhinton** [comment]
that would require HUGE amounts of development, and is not easily done. Why not use keepass as your general manager? there is even a keepass nextcloud application: https://apps.nextcloud.com/apps/keeweb
this should allow you to archieve your usecase

**Comment by newhinton** [comment]
I dont think this will be implemented in the forseeable future. It boils down to this:
If you open the vault on a pc, you already have an unencrypted copy of your passwords on said pc (in the browsers cache&memory). If it's not trustworthy, you (maybe) already compromised your passwords. Therefore, exporting encrypted would actually just automate downloading the cleartextfile, converting it to a different format (eg. keepass) and then reencrypt it. It is impossible to do that on the server, because it needs to know your vaultpassword for that. Also, exporting to a different format is not a trivial task, since custom fields are hard do migrate to a new format. 


Generally, it IS possible to implement such an export, but it requires very much work that does not add any security and also is only in a very limited way usable. (you cant create an api to automate export, since you need the server to know the password for that, also, using the "target" manager as your one and only manager seems more straightforward)

If anyone is willing to implement this feature, he or she can reopen this ticket, but i dont think that one of the remaining maintainers are picking this up, sorry :/

**Comment by bblonski** [comment]
Fair enough.  I though passman was maybe using kdbx underneath and did not realize it was a different format.  I prefer the passman browser integration, so will deal with occasionally exporting csv and importing into keepass as a backup.
