### ISSUE TITLE
"App has no update for this version available"

### ISSUE THREAD

**Issue by paulcalabro** [nextcloud/passman#659]
### Steps to reproduce
1. Go to "Settings"
2. Go to "Overview"
3. Notice should display if you can upgrade to 19.0.1:

```
A new version is available: Nextcloud 19.0.1
<SOME_NUMBER> app has no update for this version available
```

I'm currently seeing Passman listed with no updated for 19.0.1.

### Expected behaviour
I can update to Nextcloud version 19.0.1 safely.

### Actual behaviour
I get a warning message instead.

### Configuration
N/A
  
   
#### Browser log
N/A

#### Cloud log
N/A

## Feature request
N/A

**Comment by paulcalabro** [comment]
If this can't be worked on atm, do we at least know if it's safe to proceed with the upgrade? I'm reliant on Passman so I want to ensure  I can access it after the upgrade.

**Comment by ohreally** [comment]
Looking at the [list of commits](https://github.com/nextcloud/passman/commits/master), it's clear that the last commit by a human was on Nov 17 2019; since then it's only been @nextcloud-bot adding translations.

Could anybody confirm that this project is still alive?

**Comment by ohreally** [comment]
O, and by the way: no, Passman does **NOT** work after an upgrade to Nextcloud 19.

**Comment by Matthew-Hine** [comment]
Tagging @newhinton in relation to @ohreally question in thread.

**Comment by newhinton** [comment]
As i am the one who wrote the last changes since 2018, i am hesitant to confirm that this application is alive as i switched to a different app back in '19.

You may be able to get help in the telegram-group:
https://t.me/passman_general

If you decide to switch and need help exporting to a different app, feel free to comment here and i'll try to help!

**Comment by ohreally** [comment]
Hi @newhinton,

Thanks for your response.
I would appreciate a good tip for an app to switch to, and if it could import the passwords I stored in Passman, that would be a great bonus.

Thanks again,
  Rob

**Comment by newhinton** [comment]
So, if you need nextcloud as a base, there is [Passwords](https://github.com/marius-wieschollek/passwords), which is promising, except i dont know in what state client side encryption is (he was working on it though)

personally, i went the keepass route, there even is an implementation for [keeweb for nextcloud](https://apps.nextcloud.com/apps/keeweb)

if you still have nextcloud 18, you should be able to export it as csv and reimport it with the keepass implementation of your choice (or any other manager, for that matter) however, as far as i know files are not exported and may be broken. If you already upgraded to nc19, i can take a look if i can quickly cobble an exporter together, but that will not happen before the next week

**Comment by ohreally** [comment]
I'll look into those 2 apps.
I already upgraded, but don't bother creating something for me. Worst case scenario, this is a nice opportunity to change all my passwords; it's about time anyway. :)

Thanks much.

**Comment by newhinton** [comment]
it will probably be a good idea to create a last update which only allows for downloading an archive, so that other users can export their stuff. I'll talk to a dev and post it here :)

**Comment by ohreally** [comment]
@newhinton, let me save you some work...

If you enable untested app versions in NC 19, you can enable Passman, open your vaults, and export them to csv or json. Haven't tested anything else.

So I guess you only need to edit the README.

Cheers

**Comment by paulcalabro** [comment]
Thanks for the info! I'm starting to thinking Keeweb might be the way to go! @newhinton do you know if it supports OTP?

**Comment by newhinton** [comment]
It has an option to add otp-codes, but i have not used it since i use an authenticator-app.

**Comment by vwbusguy** [comment]
Passman appears to be working fine for me so far on NC 19.0.1.  I just had to "enable untested".

The Firefox add-on and the Android app continue to work, too.

**Comment by adi2k5** [comment]
Just updated to 19.0.2, and passman seem to still be working fine if anyone is curious.

**Comment by paulcalabro** [comment]
Updated to 19.0.2 as well an no issues also.

**Comment by piti-diablotin** [comment]
Works fine with NC 19.0.2 on my side too. But if it is not maintained we should have a way to move to something else for all user without them to worry on how to do the export/import. Is that possible or not at all ?

**Comment by paulcalabro** [comment]
@piti-diablotin I haven't tested it, however, there is an export feature:

![Screen Shot 2020-09-02 at 7 13 34 AM](https://user-images.githubusercontent.com/585059/91994787-de57ff00-eceb-11ea-80b9-9596a81d9d2e.png)

**Comment by vwbusguy** [comment]
For now all that we need to close this would be for someone to bump the version number in the app to up to 19.0.x and then re-upload it.  It's a one line change.  I can create a PR for it if you want, but someone with the app key will need to upload the new version to the Nextcloud store.

**Comment by vwbusguy** [comment]
Specifically, this line just needs bumped to 19: https://github.com/nextcloud/passman/blob/master/appinfo/info.xml#L45

**Comment by vwbusguy** [comment]
I created a PR to bump the supported version to Nextcloud 19 since we have several here that can attest it is functional in the current release.  It should just need to be merged and then submitted to the Nextcloud store to fix it.

**Comment by paulcalabro** [comment]
Just confirming that it works fine on 19.0.3.

**Comment by vwbusguy** [comment]
@paulcalabro Yup, WFM, too.  At this point, we're at the mercy of someone reviewing and merging the PR.

**Comment by piti-diablotin** [comment]
@paulcalabro Yes it works quite fine (tested with FF) but it is a "per user" work and I don't expect any of my users to do this. I was thinking of an automated work. But because of the E2EE I don't think it is possible. 
I also tried to import the data in the official `Password` app. It works fine. Although I understand the none necessity for E2EE with HTTPS, I feel like it is a additional barrier to MITM. Indeed, the password is never sent to the server and thus even a hacker who would gain control of the server could not decrypt the passwords. Therefore while the official `Password` app does not provide the stable E2EE I stay with Passman :) 

BTW: Would anyone interested in a Desktop app (Qt-based for Linux/Windows/Mac/(Android if I managed a few things))? I started one a while a go.

**Comment by wilya7** [comment]
I would like to ask a question to anyone reading this bug report. 

Is this app still cared for by its developers? If not, then it is probably worth it to switch to a different solution now even if it is inferior to passman. 

What happens when there will be a bug that cannot be patched so easily as in this case? For a migration plan, the sooner the better. I would like to know your opinion.

**Comment by piti-diablotin** [comment]
@wilya7 I wish I could I had more time to help maintaining the app but I don't have all the information needed to do that. Best example is that the app wors with NC19 but we cannot update this repository nor upgrade the app since it needs a signature.
The question is: can the community have access to this app to maintain it ?

**Comment by vwbusguy** [comment]
That is the question - It's not just a matter of who is willing to review Pull Requests.  There are specific individuals with access to the signing key needed to upload a release to the Nextcloud store.  It appears that those individuals are no longer active on this project, and if that's the case, it's effectively dead.

**Comment by paulcalabro** [comment]
@newhinton @brantje Are you able to assist?

**Comment by vwbusguy** [comment]
In fairness to @newhinton , it sounds like he has moved on to another password provider.  Maybe it would be good to have one last official release to give people an easier path to exporting their credentials to a new provider?

**Comment by piti-diablotin** [comment]
All the passman app is opensource and available on github so we can still fork it, make our changes, updates, fixes and provide a new app

**Comment by piti-diablotin** [comment]
Anyone knows the "howto" to do that ?

**Comment by paulcalabro** [comment]
I haven't built an app for Nextcloud yet, however, there's a section here pertaining to publishing new apps:

https://nextcloud.com/developer/
https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/index.html
