### ISSUE TITLE
2FA implementation Request

### ISSUE THREAD

**Issue by john-clark** [nextcloud/passman#667]
### Steps to reproduce
1. Install passman addon to firefox
2. Configure passman to connect to nextcloud server
3. Log in
4. Secure local database

### Expected behaviour
During step 3 when logging in, if account has 2fa enabled, user should be prompted for otp.

### Actual behaviour
No 2fa is honored

### Configuration
**Operating system**:   Windows

**Browser**:      Firefox

**Extensions that might cause interference**:   none

**Passman version**:    2.1.1

**Operating system**: Linux

**Web server:** Nginx

**Database:** mariadb

**PHP version:** 7.3
      
**cloud server:** Nextcloud

**cloud version:** 20.0.1
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
not needed - ui improvement
```
</details>   

#### Cloud log
<details>
<summary>Cloud log</summary>
```
not needed - ui improvement
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners

### Description
Check for 2fa setting and if enabled utilize it

### Benefit / value
Improve security

### Risk / caveats
Not implementing is less secure

### Sponsorship
none
 
**Are you a developer willing to implement this feature?**: yes

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by vwbusguy** [comment]
Two considerations:

One is that Nextcloud already has mfa offerings and if passman could support that for logins, it would kill two birds with one stone as enabling mfa in nextcloud now means you may need to generate an app password for passman clients (Android, browser).

The vault password in addition to the user password is itself a second factor, it's just not a good one since it's also a password.  Same goes for the client side password.  If hooking into NC login isn't an option, we could generate a per user TOTP token and use that as part of the vault unlock process somehow.  Since passman already supports TOTP, the necessary bits are there to validate the token against the current server time.  In this case, we should also advise users to make sure their server is syncing to an NTP server and any clients (phones, laptops) are also on network time as there's only a 30 second window with TOTP.

**Comment by john-clark** [comment]
It appears that passman is no longer active therefore I have migrated to passwords and I am no longer interested in this issue. Best of luck.
