### ISSUE TITLE
Files can no longer be used

### ISSUE THREAD

**Issue by Nobissoft** [nextcloud/passman#688]
Hello, I am currently using Nextcloud version 20.0.8 with Passman version 2.3.7.
Unfortunately I can not access the files that I uploaded. In a previous version I could download the file when clicking. Is this an error?
Mfg

**Comment by binsky08** [comment]
@Nobissoft this is an already known bug that exists since a few versions.
It is already fixed in #682.
As a temporary fix to download your files, you could try to open your browser dev tools and insert the following code to the js console. (After a page reload its gone)
```
function escapeHTML(s) { return s.toString().split('&').join('&amp;').split('<').join('&lt;').split('>').join('&gt;').split('"').join('&quot;').split('\'').join('&#039;'); }
```

If it does not work try it with the simpler version:
`function escapeHTML(s) { return s; }`
