### ISSUE TITLE
version 2.4.10 bump, but files not available

### ISSUE THREAD

**Issue by codejp3** [nextcloud/passman#823]
Hello,

I wanted to report missing files for the latest 2.4.10 version bump.

NC shows update available, but it fails with a 404 not found error.

Here's the error:

`"exception":[],"CustomMessage":"Client error: 'GET https://releases.passman.cc/passman_2.4.10.tar.gz' resulted in a '404 Not Found' response:\n<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found (truncated...)\n"},"id":"671256b2aa4a1"}`

Sure enough, passman_2.4.10.tar.gz does not exist at https://releases.passman.cc/

**Comment by poupounetjoyeux** [comment]
Same here 😢

**Comment by Bueddl** [comment]
having the same issue...

**Comment by binsky08** [comment]
Thanks for the report,

**the missing release file is intended and a fast fix for a previous problem we had with the original 2.4.10 release**.

Some required js files were missing in the release due to a broken step in the build process. Unfortunately I don't have dev access to the Nextcloud app store to remove the release hint.

If someone's waiting for the release to be able to update to Nextcloud 30, just do it, it also works with 2.4.9. Except a little style thing with credential icons, nothing else is affected.

Let's hope we'll get it fixed soon. @animalillo :D

**Comment by Bueddl** [comment]
Thanks for the info! FYI: I had to use `occ app:enable --force passman` as the UI rejected to enable the app even when attempting to bypass the compatibility check.

**Comment by codejp3** [comment]
2.4.9 also enabled here on NC30 and seems to be working fine.

Will upgrade as soon as the tar.gz file is available.
